name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: 'Set up skopeo'
      uses: warjiang/setup-skopeo@v0.1.3
      with:
        version: latest
    - name: 'Sync images'
      run: |
        sudo apt update && sudo apt install -yq vim skopeo libssl1.0-dev
    - name: 'Sync images'
      run: |
        df -kh
        id
        env
        skopeo --version
        skopeo copy docker://library/ubuntu:24.04 oci:/tmp/image:latest
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
