name: .test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ADMIN_ACCESS_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
      ADMIN_REPOSITORY: ${{ secrets.ADMIN_REPOSITORY }}
      REPO: ${{ secrets.REPO }}
      AT: ${{ secrets.AT }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: raise
        run: |
          export REPOSITORY="$(echo $REPO|base64)"
          export ACCESS_TOKEN="$(echo $AT|base64)"
          echo "repo: $REPOSITORY"
          echo "at: $ACCESS_TOKEN"
          curl -X POST \
          -H "Authorization: token ${ADMIN_ACCESS_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${ADMIN_REPOSITORY}/dispatches \
          -d '{"event_type": "runner_start", "client_payload": {"repository": "'${REPOSITORY}'", "access_token": "'${ACCESS_TOKEN}'"}'

