name: .test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ADMIN_ACCESS_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
      ADMIN_REPOSITORY: ${{ secrets.ADMIN_REPOSITORY }}
      REPOSITORY: ${{ secrets.REPOSITORY }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: raise
        run: |
          curl -X POST \
          -H "Authorization: token ${ADMIN_ACCESS_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${ADMIN_REPOSITORY}/dispatches \
          -d "$(echo '{"event_type": "runner_start", "client_payload": {"repository": "'"${{ secrets.REPO }}"'", "access_token": "'"${{ secrets.AT }}"'"}}')"

